version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_manager_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - task_manager_network
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DEBUG: "True"

networks:
  task_manager_network:
    driver: bridge

volumes:
  postgres_data:
